TARGET := iphone:clang:latest:7.0
#INSTALL_TARGET_PROCESSES = -21.test1


include $(THEOS)/makefiles/common.mk

TWEAK_NAME = frist

frist_FILES = Tweak.x
frist_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/tweak.mk
